# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Henry Lau
tagline:          'Digital Science Communicator'
description:      'Personal website for Henry Lau, a digital science communicator.'
url:              http://henryjameslau.github.io
baseurl:          /

author:
  name:           'Henry Lau'
  url:            https://twitter.com/henryjameslau

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
