#PAGES_REPO_NWO
repository: henryjameslau/henryjameslau.github.io.git

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Henry Lau
tagline:          'Digital Science Communicator'
description:      'Digital Science Communicator'
url:              http://www.henrylau.co.uk
baseurl:          ''

author:
  name:           'Henry Lau'
  url:            https://twitter.com/henryjameslau

paginate:         5

# Analytics
tracking_id:	  "UA-99583778-1"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde 