# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Henry Lau
tagline:          'Henry Lau. Digital Science Communicator'
description:      'A personal website for Henry Lau.'
url:              http://henryjameslau.github.io
baseurl:          /

author:
  name:           'Henry Lau'
  url:            https://twitter.com/henryjameslau

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
