# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Henry Lau
tagline:          'Digital Science Communicator'
description:      'Digital Science Communicator'
url:              http://henryjameslau.github.io
baseurl:          /

author:
  name:           'Henry Lau'
  url:            https://twitter.com/henryjameslau

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
